### ISSUE TITLE
Can't start after most recent update

### ISSUE THREAD

**Issue by jbeck22** [se1exin/Cleanarr#88]
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    from flask import Flask, jsonify, request, send_file
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/local/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
Running inside /app/prestart.sh, you could add migrations to this file, e.g.:

#! /usr/bin/env sh

# Let the DB start
sleep 10;
# Run migrations
alembic upgrade head

2023-04-17 10:00:15,868 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-04-17 10:00:15,868 INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2023-04-17 10:00:15,903 INFO RPC interface 'supervisor' initialized
2023-04-17 10:00:15,903 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-04-17 10:00:15,904 INFO supervisord started with pid 1
2023-04-17 10:00:16,907 INFO spawned: 'quit_on_failure' with pid 8
2023-04-17 10:00:16,911 INFO spawned: 'nginx' with pid 9
2023-04-17 10:00:16,914 INFO spawned: 'uwsgi' with pid 10
2023-04-17 10:00:16,918 INFO success: nginx entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-04-17 10:00:16,918 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2023-04-17 10:00:18,404 INFO success: quit_on_failure entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-04-17 10:00:20,203 INFO exited: uwsgi (exit status 22; not expected)
2023-04-17 10:00:21,206 WARN received SIGTERM indicating exit request
2023-04-17 10:00:21,206 INFO waiting for quit_on_failure, nginx to die
2023-04-17 10:00:22,230 INFO stopped: nginx (exit status 0)
2023-04-17 10:00:22,231 INFO stopped: quit_on_failure (terminated by SIGTERM)

** Press ANY KEY to close this window ** 

Running on unRaid docker

**Comment by se1exin** [comment]
Thanks for error report. The last version was bad, I've rebuilt the container with the last working version (2.2.0) which is now tagged as `latest` on dockerhub. Please pull the latest version and let me know how it goes for you.

**Comment by jbeck22** [comment]
> Thanks for error report. The last version was bad, I've rebuilt the container with the last working version (2.2.0) which is now tagged as `latest` on dockerhub. Please pull the latest version and let me know how it goes for you.

Yes -- A force update in unRaid worked.  Thanks!
